"use client";
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeneralContextProvider } from "@/context/GeneralContext";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  console.log(pathname);
  return (
    <html lang="en" className="h-full w-full ">
      <body className={`${inter.className} flex-1`}>
        <GeneralContextProvider>
          {pathname.startsWith("/login") ||
          pathname.startsWith("/signup") ||
          pathname.startsWith("/home") ||
          pathname === "/" ? (
            <>{children}</>
          ) : (
            <MainLayout>{children}</MainLayout>
          )}
        </GeneralContextProvider>
      </body>
    </html>
  );
}
